Web Dev exercise: Version Control

Objective: Gain experience using a collaborative version control repository for html code.

Overview: Version control is one of the most fundamental software engineering concepts, providing a history of changes 
that are made and accountability for who made the changes. A version control server also serves as a storage mechanism that 
can alleviate the need for local backups for some of your files. We will use GitHub as an example of a version control
system that is used by many professional organizations and open source projects. A GitHub account can serve as part of
a professional portfolio that hiring companies use to evaluate job candidates.


Part A - setup
--------------
* Go to https://github.com/, click Sign up, and create a free account. (Be professional when choosing a username.)
* Check your email and follow the link to confirm your email address (you may need to log in to GitHub again). 
* Tell a mentor your GitHub username so they can give you permission to push to the repo.

Mentor:

* Log in to GitHub.com using your account that has admin rights for the Adamson-ptech organization.
* Go to https://github.com/Adamson-ptech.
* Click "Teams".
* Click "webdev2018team", then "Members", then "Add a member".
* Enter the username, making sure it matches (there may be many similar usernames), then click "Invite" and "Add...".

Student:

* Go to https://github.com/orgs/Adamson-ptech/ and click "View invitation" (or click the link from your invitation email).
* Click "Join Adamson-ptech".


Part B - create content
-----------------------

Now add a folder and an html file in that folder -

* Go to the repository in your browser - https://github.com/Adamson-ptech/webdev2018.
* Click "WebContent".
* Click on the folder for your class - "09.05_class", "10.53_class", or "01.55_class".
* Click the "Create new file" button.
* Where it says "Name your file", type in a folder name using your first name and last initial, like "JaneD" for Jane Doe, followed by a forward slash "/". Don't forget the slash - this is what makes a new folder.
* A new box opens for you to type a file name. Type "index.html".
* For the content of the file, enter the name of an online business you might light to set up some day. It doesn't have to be valid html yet.
* Scoll to the bottom of the page where it says "Commit new file". 
* In the small text box that says "Create new file", enter a short message about why you're committing the file, like "New web page by" and your name
* Click the green "Commit new file" button.

Congratulations - you have commited a file to GitHub!
